CREATE TABLE IF NOT EXISTS tbl_photos (
img_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, 
img_name VARCHAR(255) NOT NULL,
img_path VARCHAR(255) NOT NULL, 
img_type VARCHAR(255) NOT NULL,
img_title VARCHAR(255) NOT NULL 
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
